"""Task model

Revision ID: 49f278c513b3
Revises: 
Create Date: 2025-08-21 19:59:18.381612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f278c513b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_tasks')),
    sa.UniqueConstraint('uuid', name=op.f('uq_tasks_uuid'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    enum = sa.Enum('CREATED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus')
    enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
